config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :schedules do
    resources :comments, only: [:new, :create, :destroy]
  end
  root to: "schedules#index"
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :schedule
  belongs_to :user

  validates :text, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules
  has_many :comments
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @schedule = Schedule.find(params[:schedule_id])
    @comment = Comment.new
  end

  def create
    comment = Comment.create(comment_params)
    redirect_to "/schedules/#{comment.schedule.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, schedule_id: params[:schedule_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room =  Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.all
  end
  
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end


private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :redirect_root, only: [:edit]

  def index
    @calendars = Schedule.order('start_time ASC')
    @schedules = Schedule.where("start_time > ?",Date.today).order('start_time ASC')
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @schedule.comments.includes(:user)
  end

  def edit
  end

  
  def update
    if @schedule.update(schedule_params)
      redirect_to schedule_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @schedule.destroy && current_user.id == @schedule.user_id
  end


  private

  def schedule_params
    params.require(:schedule).permit(:title, :start_time, :place, :person, :practice, :others).merge(user_id: current_user.id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
 
  def redirect_root
    redirect_to root_path unless current_user.id == @schedule.user_id 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/comments/new.html.erb
<%= render "shared/header" %>

<div class ="main">
   <div class = "comment-form">
      <%= form_with(model: [@schedule, @comment], local: true)  do |f| %>
         <%= f.text_area :text, placeholder: "コメント・フィードバック等", size: "70x15" %>
         <div class="submit">
        <%= f.submit %>
      </div>

      <%= link_to "戻る",schedule_path(@schedule.id) , class: 'back'%>
      <% end %>
   </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="group-name"><%= @room.name %></div>
  <div class="chat-close">
    <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
  </div>
</div>
<div class="chat-main">
   <%= render partial: 'message', collection: @messages %>
</div>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <%= message.created_at.strftime('%-m/%d %H:%M') %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '400x400'), class: 'message-image' if message.image.attached?  %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-top">
  <div class="user-name">
    <%= current_user.name %>
  </div>
  <div class="create-chat">
    <%= link_to"チャットを作成する",  new_room_path %>
  </div>
</div>
<div class="side-main">
  <% current_user.rooms.each do |room| %>
    <div class="chat-room">
      <div class="chat-name">
         <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<%= render "shared/header" %>

<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/header" %>

<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>

    <%= render 'shared/error_messages', model: f.object %>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]", class = 'select-room'>
         <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
             <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>


<%= render "shared/footer" %>

app/views/schedules/edit.html.erb
<%= render "shared/header" %>

<div class ="main">
  <div class = "new-schedule-form">
    <%= form_with(model: @schedule, local: true) do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <div class="weight-bold-text">
          件名
      </div>
      <%= f.text_field :title, class:"title", id:"title", placeholder:"件名" %>

      <div class="weight-bold-text">
        日時
      </div>
      <%= f.datetime_select :start_time, class:"start_time", id:"start_time" %>

      <div class="weight-bold-text">
          場所
      </div>
      <%= f.text_area :place, class:"place", id:"place", placeholder:"場所" ,rows:"2" %>


      <div class="weight-bold-text">
          参加者
      </div>
      <%= f.text_field :person, class:"person", id:"person", placeholder:"参加者" %>

      <div class="weight-bold-text">
          練習メニュー
      </div>
      <%= f.text_area :practice, class:"practice", id:"practice", placeholder:"練習メニュー" ,rows:"7" ,maxlength:"1000" %>

      <div class="weight-bold-text">
          その他
      </div>
      <%= f.text_area :others, class:"others", id:"others", placeholder:"その他連絡事項等" ,rows:"4" ,maxlength:"1000" %>
      
      <div class="submit">
        <%= f.submit %>
      </div>

      <%= link_to "戻る", schedule_path(@schedule.id), class: 'back'%>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/schedules/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="recent-schedule" >
    <h4>＜直近の予定＞</h4>
    <% unless @schedules.exists? %>
        直近の予定はありません
    <% end %>  
      <% @schedules.each do |schedule| %>
        <div class="recent-schedule-box">
          <%=  schedule.start_time.strftime('%-m/%d %H:%M') %>
          <%=  schedule.title %>
          <div class = person >
          <% if schedule.person.present? %>
          参加者：
          <%= schedule.person %>
          <% else %>  
          未定
          <% end %>
          <%= link_to "詳細",schedule_path(schedule.id), class: 'show-buttan'%>
          </div>
        </div>
      <%end%>
  </div>
  

  <div class = "new-schedule">
  <%= link_to "新規予定作成", new_schedule_path, class: 'new-schedule'%>
  </div>
  <%= month_calendar events: @calendars do |date, calendars| %>
    <%= date.day %>

    <% calendars.each do |calendar| %>
      <div>
        <%= link_to calendar.title, schedule_path(calendar.id), class: 'calendar-schedule'%>
      </div>
    <% end %>
  <% end %>

</div>

<%= render "shared/footer" %>

app/views/schedules/new.html.erb
<%= render "shared/header" %>

<div class ="main">
  <div class = "new-schedule-form">
    <%= form_with(model: @schedule, local: true) do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <div class="weight-bold-text">
          件名
      </div>
      <%= f.text_field :title, class:"title", id:"title", placeholder:"件名" %>

      <div class="weight-bold-text">
        日時
      </div>
      <%= f.datetime_select :start_time, class:"start_time", id:"start_time", :minute_step => 15 %>

      <div class="weight-bold-text">
          場所
      </div>
      <%= f.text_area :place, class:"place", id:"place", placeholder:"場所" ,rows:"2" %>


      <div class="weight-bold-text">
          参加者
      </div>
      <%= f.text_field :person, class:"person", id:"person", placeholder:"参加者" %>

      <div class="weight-bold-text">
          練習メニュー
      </div>
      <%= f.text_area :practice, class:"practice", id:"practice", placeholder:"練習メニュー" ,rows:"7" ,maxlength:"1000" %>

      <div class="weight-bold-text">
          その他
      </div>
      <%= f.text_area :others, class:"others", id:"others", placeholder:"その他連絡事項等" ,rows:"7" ,maxlength:"1000" %>
      

      <div class="submit">
        <%= f.submit %>
      </div>

      <%= link_to "戻る", root_path, class: 'back'%>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/schedules/show.html.erb
<%= render "shared/header" %>

<div class = "main">
  <div class = "schedule-show">

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">件名</div>
      <div class = schedule-show-box><%= @schedule.title %></div>
    </div>

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">日時</div>
      <div class = schedule-show-box><%= @schedule.start_time.strftime('%-m/%d %H:%M') %></div>
    </div>

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">場所</div>
      <div class = schedule-show-box><%= @schedule.place %></div>
    </div>

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">参加者</div>
      <div class = schedule-show-box><%= @schedule.person %></div>
    </div>

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">練習メニュー</div>
      <div class = schedule-show-longbox><%= simple_format(@schedule.practice) %></div>
    </div>

    <div class ="schedule-show-set">
      <div class ="schedule-show-title">その他</div>
      <div class = schedule-show-middlebox><%= simple_format(@schedule.others) %></div>
    </div>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.name %>：</strong>
          <%= simple_format(comment.text) %>
        </p>
      <% end %>
    </div>

    <%= link_to "コメントする", new_schedule_comment_path(@schedule.id), class: 'button'%>

    <% if current_user.id == @schedule.user_id %>
    <%= link_to "編集", edit_schedule_path, class: 'button'%>

    <%= link_to "削除", schedule_path(@schedule.id), method: :delete, class: 'button' %>
    <% end %>
    
    <%= link_to "戻る", root_path, class: 'back'%>

  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div>
  <%= link_to image_tag("calendar.png", class:"calendar-image"), root_path %>
  </div>
   <div >
  <%= link_to image_tag("comment.png", class:"chat-image"), rooms_path %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
   <div class = "header-main">
   <%= link_to "team-app", root_path, class: 'header-left'%>
    <div class = "header-right">
      <div class = "user-name"><%= current_user.name %></div>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout'%>
    </div>
   </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>